fail_fast: false

repos:
  - hooks:
      - id: black
        exclude: ^tests/
    repo: https://github.com/psf/black
    rev: 23.7.0

  - hooks:
      - id: pylint
        exclude: ^tests/
        name: pylint
        entry: pylint
        language: system
        types: [python]
        require_serial: true
    repo: local

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.902
    hooks:
      - id: mypy
        exclude: ^tests/