name: Build and write pipeline
on:
  pull_request:
    branches:
      - develop
      - main
  push:
    tags:
      - '*.*.*'
      - '*.*.*-rc*'
jobs:
  build-and-push-pipeline:
    uses: softwaremmm/pipeline-builder/.github/workflows/build_pipeline.yaml@main
    with:
      pipeline_name: myco
      main_pipeline: gpas-tb-workflow
    secrets: inherit
    permissions:
      contents: read
      packages: write