name: Pull in subworkflows
on: workflow_dispatch

jobs:
  deploy:
    concurrency: pull_sub_workflows
    runs-on: ubuntu-latest
    steps:
      - name: Clone subworkflows
        run: |
          set -xe
          #Make sure we have git, tar and jq installed
          sudo apt update --fix-missing
          sudo apt install -y git jq tar gzip

          #Docker login so we can pull
          docker login lhr.ocir.io -u ${{secrets.OCR_USERNAME}} -p $(echo "${{secrets.OCR_TOKEN}}")

          #Git setup so we can actually push
          git config --global user.email "it-support@gpas.global"
          git config --global user.name "gpas-github-bot"

          #We want to start in this repo
          git clone https://${{secrets.PAT_TOKEN}}@github.com/GlobalPathogenAnalysisService/gpas-tb-workflow.git
          cd gpas-tb-workflow

          #Find out what the next version will be
          #Based on SARS-CoV2_workflows actiont to do the same
          #This requires an actual release first though
          CURRENT_VERSION=$(git tag -l --sort=-version:refname | head -n 1)
          echo "Current Version = $CURRENT_VERSION"
          readarray -d . -t strarr <<< "$CURRENT_VERSION"
          ((strarr[-1]+=1))
          NEW_VERSION="${strarr[0]}"
          for elem in "${strarr[@]:1}";do NEW_VERSION="$NEW_VERSION.$elem"; done
          echo "This version = $NEW_VERSION"
          
          git checkout main
          git checkout -b $NEW_VERSION-branch main

          original_path=$(pwd)

          #Remove the contents of the dummy data dir
          rm -rf data/*

          #Pull in all of the sub workflows
          mkdir -p sub_workflows
          cd sub_workflows

          #Make sure there's nothing there to start with
          rm -rf ./*

          #Temp folder to make extracting files easy
          mkdir -p tmp

          get_software_versions(){
            local container_tag=$1

            #Pull apart the container name and the tag name
            local container=$(echo $container_tag | cut -d : -f 1)
            local tag=$(echo $container_tag | cut -d : -f 2)

            #IFS changes to force `for` loop over lines not spaces
            DEFAULT_IFS=$(echo $IFS)
            IFS=$'\n'

            for tool in $(cat $original_path/get-container-tools.json | jq -r ".\"${container}\"[]");
            do
                #As some tools print version to stderr (as does docker pull)
                #Pull the containers before doing docker run
                DOCKER_PULL="sudo docker pull "
                DOCKER_PULL+="$container:$tag"
                eval $DOCKER_PULL

                #Pull out the command from the tools JSON
                command=$(cat $original_path/get-software-version-commands.json| jq -r ".\"$tool\"")
                echo $tool --\> $command 

                #Build docker run command
                DOCKER_RUN="sudo docker run "
                DOCKER_RUN+="$container:$tag $command"

                #Get version of this tool
                echo $DOCKER_RUN
                eval $DOCKER_RUN > tmp.txt

                #Ensure values are single line
                v=$(cat tmp.txt | sed 's/$/\\n/' | tr -d '\n')
                #Remove trailing string literal \n
                v=${v%??}
                rm tmp.txt

                echo -e $container:$tag --\> $tool --\> $v >> software_versions.txt

            done

            IFS=$(echo $DEFAULT_IFS)

          }

          for repo in $(cat ../includerepos.txt); do
            #Clone the repo
            git clone https://${{secrets.PAT_TOKEN}}@github.com/$repo.git

            #Pull out the repo name (without `GlobalPathogenAnalysisService/`)
            r=$(basename $repo)

            cd $r
          
            #Use most recent tags
            git fetch --all
            git fetch --tags

            pipeline_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
            echo -n "$r = $pipeline_tag\n" >> ../pipeline_versions.txt
            git checkout $pipeline_tag

            cd ..

            #Now we have the latest release, cut out everything not-required
            rm -rf $r/.git*
            
            #If a minimal files has been declared, use it. Otherwise just take everything for now
            if [ -s $r/minimal_files.txt ]; then
              mv $r/* tmp

              for f in $(cat tmp/minimal_files.txt);do
                #Retain dir structure
                mkdir -p $r/$(dirname $f)
                cp tmp/$f $r/$(dirname $f)
              done

              #Now we have just the files required to run, clean up and move on
              rm -rf tmp/*
            fi

            #Find which containers are used within the nextflow as a single \n separated line
            #One version for `container = "<foo>"`, one for `container = '<foo>'`
            echo -nE $(find $r | grep -E "\.nf" | xargs cat | grep -E '\w*container\ *=? \ *".*"' | cut -d \" -f 2 | uniq | sed 's/$/\\n/' | tr -d '\n') >> container_versions.txt
            echo -nE $(find $r | grep -E "\.nf" | xargs cat | grep -E "\w*container\ *=? \ *'.*'" | cut -d \' -f 2 | uniq | sed 's/$/\\n/' | tr -d '\n') >> container_versions.txt
          done

          for container in $(cat container_versions.txt | sed 's/\\n/\'$'\n''/g');
          do
              echo $container
              get_software_versions $container
              echo
              echo
          done

          python3 ../jsonify-software-versions.py software_versions.txt

          rm software_versions.txt

          echo -n gpas-tb-workflow = $NEW_VERSION >> pipeline_versions.txt

          #Ensure we add everything by cd-ing to the main git dir
          cd $original_path

          #Push if there is anything to push
          git add . || echo "No changes to add"
          git commit -m "[bot] Update WP8 to $NEW_VERSION" || echo "No changes to commit"
          git push origin $NEW_VERSION-branch || echo "No changes to push"

          #Create a release
          #The JSON here is disgusting because of the \"
          # but it's the only way to allow variable interpolation within a JSON string
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{secrets.PAT_TOKEN}}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/GlobalPathogenAnalysisService/gpas-tb-workflow/releases \
            -d "{\"tag_name\": \"$NEW_VERSION\", \"target_commitish\": \"$NEW_VERSION-branch\", \"name\": \"$NEW_VERSION\", \"body\": \"# Pipeline versions\n$(cat sub_workflows/pipeline_versions.txt)\n# Container versions\n$(cat sub_workflows/container_versions.txt)\", \"draft\": false, \"prerelease\": false, \"generate_release_notes\": false}" > gh_release.json

          #For debugging...
          cat gh_release.json

          #Parse the JSON response to get the ID of the release we just created
          RELEASE_ID=$(cat gh_release.json | jq ".id")
          rm gh_release.json

          #Create release asset
          cd ..
          mkdir -p $NEW_VERSION
          cp -r gpas-tb-workflow/* $NEW_VERSION
          tar -czf $NEW_VERSION.tar.gz $NEW_VERSION
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{secrets.PAT_TOKEN}}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "Content-Type: application/octet-stream" \
            "https://uploads.github.com/repos/GlobalPathogenAnalysisService/gpas-tb-workflow/releases/$RELEASE_ID/assets?name=$NEW_VERSION.tar.gz" \
            --data-binary "@$NEW_VERSION.tar.gz"
          


          #Clean up the branch now we're done with it
          cd gpas-tb-workflow
          git push origin --delete $NEW_VERSION-branch


          
