name: Get versions
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get versions
        run: |
          set -xe

          sudo apt update
          sudo apt install git

          #We want to start in this repo
          git clone https://${{secrets.PAT_TOKEN}}@github.com/GlobalPathogenAnalysisService/gpas-tb-workflow.git
          cd gpas-tb-workflow
          git checkout add-software-versions


          #Change IFS so we only interpret newlines as splits for `for` loops
          DEFAULT_IFS=$(echo $IFS)
          IFS=$'\n'

          for container in $(cat get-software-version-commands.json | jq "keys[]");
          do
            for command in $(cat get-software-version-commands.json | jq ".${container}[]" | tr -d \");
            do
              echo sudo docker run $(echo $container | tr -d \"):latest $command
              echo $(echo $container | tr -d \") --> $command = foo
            done
          done

          IFS=$(echo $DEFAULT_IFS)



