name: Test on dispatch
on: [push, workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Do something
        run: |
          echo -e "Got an action running via dispatch"
          