name: Pull in subworkflows
on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone subworkflows
        run: |
          #Make sure we have git installed
          sudo apt update --fix-missing
          sudo apt install git

          #Git setup so we can actually push
          git config --global user.email "jeremywesthead3@gmail.com"
          git config --global user.name "JeremyWesthead"

          #We want to start in this repo
          git clone https://${{secrets.PAT_TOKEN}}@github.com/GlobalPathogenAnalysisService/gpas-tb-workflow.git
          cd gpas-tb-workflow
          git checkout test-action

          #Make some changes
          mkdir -p sub_workflows
          echo "some data here" > sub_workflows/test_data.txt

          #Push
          git add .
          git commit -m "test adding from workflow"
          git push
          