name: Get versions
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get versions
        run: |
          set -xe

          #Change IFS so we only interpret newlines as splits for `for` loops
          DEFAULT_IFS=$(echo $IFS)
          IFS=$'\n'

          for container in $(cat get-software-version-commands.json | jq "keys[]");
          do
            for command in $(cat get-software-version-commands.json | jq ".${container}[]" | tr -d \");
            do
              echo $(echo $container | tr -d \") --> $command = $(sudo docker run $(echo $container | tr -d \"):latest $command)
            done
          done

          IFS=$(echo $DEFAULT_IFS)



