name: Pull in subworkflows
on: workflow_dispatch

jobs:
  deploy:
    concurrency: pull_sub_workflows
    runs-on: ubuntu-latest
    steps:
      - name: Clone subworkflows
        run: |
          #Make sure we have git installed
          sudo apt update --fix-missing
          sudo apt install -y git

          #Git setup so we can actually push
          git config --global user.email "jeremywesthead3@gmail.com"
          git config --global user.name "JeremyWesthead"

          #We want to start in this repo
          git clone https://${{secrets.PAT_TOKEN}}@github.com/GlobalPathogenAnalysisService/gpas-tb-workflow.git
          cd gpas-tb-workflow
          git checkout test-action

          #Pull in all of the sub workflows
          mkdir -p sub_workflows
          cd sub_workflows

          #Make sure there's nothing there to start with
          rm -rf ./*

          #Temp folder to make extracting files easy
          mkdir -p tmp

          for repo in $(cat ../includerepos.txt); do
            #Clone the repo
            git clone https://${{secrets.PAT_TOKEN}}@github.com/$repo.git

            #Pull out the repo name (without `GlobalPathogenAnalysisService/`)
            r=$(basename $repo)

            cd $r
          
            #Use most recent tags
            git fetch --all
            git fetch --tags

            pipeline_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
            echo $r = $pipeline_tag >> ../pipeline_versions.txt
            git checkout $pipeline_tag

            cd ..

            #Now we have the latest release, cut out everything not-required
            rm -rf $r/.git*
            mv $r/* tmp

            for f in $(cat tmp/minimal_files.txt); do
              mv tmp/$f $r
            done

            #Now we have just the files required to run, clean up and move on
            rm -rf tmp/*

            #Find which containers are used within the nextflow
            find $r | grep -E "\.nf" | xargs cat | grep '\w*container\ *= \ *".*"' | cut -d \" -f 2 | uniq >> container_versions.txt

          done

          #Push
          git add . || echo "No changes to add"
          git commit -m "[bot] test" || echo "No changes to commit"
          git push || echo "No changes to push"

          #Create release notes
          echo '{
            "tag_name":"v0.0.1",
            "target_commitish":"test-action",
            "name":"v0.0.1",' >> release_notes.json

          echo "\"body\"":"\"Test release from CICD\nPipeline versions\n$(cat pipeline_versions.txt)\nContainer versions\n$(cat container_versions.txt)\"", >> release_notes.json
          
          echo '"draft":true,
            "prerelease":true,
            "generate_release_notes":false
          }' >> release_notes.json

          #Create release using github API
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{secrets.PAT_TOKEN}}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/GlobalPathogenAnalysisService/gpas-tb-workflow/releases \
            -d \'$(cat release_notes.json)\'


          